# GitHub Action that uses Standard to reformat the JavaScript code in an incoming pull request.
# If all JavaScript code in the pull request is already Standard Style then this Action does nothing.
# Othewrwise, Standard --fix is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: autostandard
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
    #  max-parallel: 1
    #  matrix:
    #    node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x  # ${{ matrix.node-version }}
      - name: npx standard
        run: npx standard
      - name: If needed, commit standard --fix changes to the pull request
        if: failure()
        run: |
          standard --fix .
          git config --global user.name 'autostandard'
          git config --global user.email 'cclauss@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format JavaScript code to be Standard Style"
          git push
